const swaggerUi = require('swagger-ui-express');
const swaggerJSDoc = require('swagger-jsdoc');

const swaggerDefinition = {
    info: {
        title: 'Server API',
        version: '1.0.0',
        description: 'Server API with autogenerated swagger doc',
    },
};

const options = {
    swaggerDefinition,
    apis: [__dirname + '/routes.js'],
};

const swaggerSpec = swaggerJSDoc(options);

module.exports = app =>
    app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));